[package]
name = "lox-language-interpreter-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "7.2.0"                               
bytes = "1.3.0"                                  
thiserror = "1.0.38"
clap = { version = "4.5.23", features = ["derive"] }      
