[package]
name = "lox-language-interpreter-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "7.2.0"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
thiserror = "1.0.38"    
